"""
Comprehensive Pokemon database with correct National Pokedex IDs.
Contains ALL 1025 Pokemon from Generations 1-9.
Fixed to resolve sprite and type issues.
"""

POKEMON_DATA = {
    "Bulbasaur": {"id": 1, "types": ['Grass', 'Poison'], "generation": 1},
    "Ivysaur": {"id": 2, "types": ['Grass', 'Poison'], "generation": 1},
    "Venusaur": {"id": 3, "types": ['Grass', 'Poison'], "generation": 1},
    "Charmander": {"id": 4, "types": ['Fire'], "generation": 1},
    "Charmeleon": {"id": 5, "types": ['Fire'], "generation": 1},
    "Charizard": {"id": 6, "types": ['Fire', 'Flying'], "generation": 1},
    "Squirtle": {"id": 7, "types": ['Water'], "generation": 1},
    "Wartortle": {"id": 8, "types": ['Water'], "generation": 1},
    "Blastoise": {"id": 9, "types": ['Water'], "generation": 1},
    "Caterpie": {"id": 10, "types": ['Bug'], "generation": 1},
    "Metapod": {"id": 11, "types": ['Bug'], "generation": 1},
    "Butterfree": {"id": 12, "types": ['Bug', 'Flying'], "generation": 1},
    "Weedle": {"id": 13, "types": ['Bug', 'Poison'], "generation": 1},
    "Kakuna": {"id": 14, "types": ['Bug', 'Poison'], "generation": 1},
    "Beedrill": {"id": 15, "types": ['Bug', 'Poison'], "generation": 1},
    "Pidgey": {"id": 16, "types": ['Normal', 'Flying'], "generation": 1},
    "Pidgeotto": {"id": 17, "types": ['Normal', 'Flying'], "generation": 1},
    "Pidgeot": {"id": 18, "types": ['Normal', 'Flying'], "generation": 1},
    "Rattata": {"id": 19, "types": ['Normal'], "generation": 1},
    "Raticate": {"id": 20, "types": ['Normal'], "generation": 1},
    "Spearow": {"id": 21, "types": ['Normal', 'Flying'], "generation": 1},
    "Fearow": {"id": 22, "types": ['Normal', 'Flying'], "generation": 1},
    "Ekans": {"id": 23, "types": ['Poison'], "generation": 1},
    "Arbok": {"id": 24, "types": ['Poison'], "generation": 1},
    "Pikachu": {"id": 25, "types": ['Electric'], "generation": 1},
    "Raichu": {"id": 26, "types": ['Electric'], "generation": 1},
    "Sandshrew": {"id": 27, "types": ['Ground'], "generation": 1},
    "Sandslash": {"id": 28, "types": ['Ground'], "generation": 1},
    "Nidoran F": {"id": 29, "types": ['Poison'], "generation": 1},
    "Nidorina": {"id": 30, "types": ['Poison'], "generation": 1},
    "Nidoqueen": {"id": 31, "types": ['Poison', 'Ground'], "generation": 1},
    "Nidoran M": {"id": 32, "types": ['Poison'], "generation": 1},
    "Nidorino": {"id": 33, "types": ['Poison'], "generation": 1},
    "Nidoking": {"id": 34, "types": ['Poison', 'Ground'], "generation": 1},
    "Clefairy": {"id": 35, "types": ['Fairy'], "generation": 1},
    "Clefable": {"id": 36, "types": ['Fairy'], "generation": 1},
    "Vulpix": {"id": 37, "types": ['Fire'], "generation": 1},
    "Ninetales": {"id": 38, "types": ['Fire'], "generation": 1},
    "Jigglypuff": {"id": 39, "types": ['Normal', 'Fairy'], "generation": 1},
    "Wigglytuff": {"id": 40, "types": ['Normal', 'Fairy'], "generation": 1},
    "Zubat": {"id": 41, "types": ['Poison', 'Flying'], "generation": 1},
    "Golbat": {"id": 42, "types": ['Poison', 'Flying'], "generation": 1},
    "Oddish": {"id": 43, "types": ['Grass', 'Poison'], "generation": 1},
    "Gloom": {"id": 44, "types": ['Grass', 'Poison'], "generation": 1},
    "Vileplume": {"id": 45, "types": ['Grass', 'Poison'], "generation": 1},
    "Paras": {"id": 46, "types": ['Bug', 'Grass'], "generation": 1},
    "Parasect": {"id": 47, "types": ['Bug', 'Grass'], "generation": 1},
    "Venonat": {"id": 48, "types": ['Bug', 'Poison'], "generation": 1},
    "Venomoth": {"id": 49, "types": ['Bug', 'Poison'], "generation": 1},
    "Diglett": {"id": 50, "types": ['Ground'], "generation": 1},
    "Dugtrio": {"id": 51, "types": ['Ground'], "generation": 1},
    "Meowth": {"id": 52, "types": ['Normal'], "generation": 1},
    "Persian": {"id": 53, "types": ['Normal'], "generation": 1},
    "Psyduck": {"id": 54, "types": ['Water'], "generation": 1},
    "Golduck": {"id": 55, "types": ['Water'], "generation": 1},
    "Mankey": {"id": 56, "types": ['Fighting'], "generation": 1},
    "Primeape": {"id": 57, "types": ['Fighting'], "generation": 1},
    "Growlithe": {"id": 58, "types": ['Fire'], "generation": 1},
    "Arcanine": {"id": 59, "types": ['Fire'], "generation": 1},
    "Poliwag": {"id": 60, "types": ['Water'], "generation": 1},
    "Poliwhirl": {"id": 61, "types": ['Water'], "generation": 1},
    "Poliwrath": {"id": 62, "types": ['Water', 'Fighting'], "generation": 1},
    "Abra": {"id": 63, "types": ['Psychic'], "generation": 1},
    "Kadabra": {"id": 64, "types": ['Psychic'], "generation": 1},
    "Alakazam": {"id": 65, "types": ['Psychic'], "generation": 1},
    "Machop": {"id": 66, "types": ['Fighting'], "generation": 1},
    "Machoke": {"id": 67, "types": ['Fighting'], "generation": 1},
    "Machamp": {"id": 68, "types": ['Fighting'], "generation": 1},
    "Bellsprout": {"id": 69, "types": ['Grass', 'Poison'], "generation": 1},
    "Weepinbell": {"id": 70, "types": ['Grass', 'Poison'], "generation": 1},
    "Victreebel": {"id": 71, "types": ['Grass', 'Poison'], "generation": 1},
    "Tentacool": {"id": 72, "types": ['Water', 'Poison'], "generation": 1},
    "Tentacruel": {"id": 73, "types": ['Water', 'Poison'], "generation": 1},
    "Geodude": {"id": 74, "types": ['Rock', 'Ground'], "generation": 1},
    "Graveler": {"id": 75, "types": ['Rock', 'Ground'], "generation": 1},
    "Golem": {"id": 76, "types": ['Rock', 'Ground'], "generation": 1},
    "Ponyta": {"id": 77, "types": ['Fire'], "generation": 1},
    "Rapidash": {"id": 78, "types": ['Fire'], "generation": 1},
    "Slowpoke": {"id": 79, "types": ['Water', 'Psychic'], "generation": 1},
    "Slowbro": {"id": 80, "types": ['Water', 'Psychic'], "generation": 1},
    "Magnemite": {"id": 81, "types": ['Electric', 'Steel'], "generation": 1},
    "Magneton": {"id": 82, "types": ['Electric', 'Steel'], "generation": 1},
    "Farfetch'd": {"id": 83, "types": ['Normal', 'Flying'], "generation": 1},
    "Doduo": {"id": 84, "types": ['Normal', 'Flying'], "generation": 1},
    "Dodrio": {"id": 85, "types": ['Normal', 'Flying'], "generation": 1},
    "Seel": {"id": 86, "types": ['Water'], "generation": 1},
    "Dewgong": {"id": 87, "types": ['Water', 'Ice'], "generation": 1},
    "Grimer": {"id": 88, "types": ['Poison'], "generation": 1},
    "Muk": {"id": 89, "types": ['Poison'], "generation": 1},
    "Shellder": {"id": 90, "types": ['Water'], "generation": 1},
    "Cloyster": {"id": 91, "types": ['Water', 'Ice'], "generation": 1},
    "Gastly": {"id": 92, "types": ['Ghost', 'Poison'], "generation": 1},
    "Haunter": {"id": 93, "types": ['Ghost', 'Poison'], "generation": 1},
    "Gengar": {"id": 94, "types": ['Ghost', 'Poison'], "generation": 1},
    "Onix": {"id": 95, "types": ['Rock', 'Ground'], "generation": 1},
    "Drowzee": {"id": 96, "types": ['Psychic'], "generation": 1},
    "Hypno": {"id": 97, "types": ['Psychic'], "generation": 1},
    "Krabby": {"id": 98, "types": ['Water'], "generation": 1},
    "Kingler": {"id": 99, "types": ['Water'], "generation": 1},
    "Voltorb": {"id": 100, "types": ['Electric'], "generation": 1},
    "Electrode": {"id": 101, "types": ['Electric'], "generation": 1},
    "Exeggcute": {"id": 102, "types": ['Grass', 'Psychic'], "generation": 1},
    "Exeggutor": {"id": 103, "types": ['Grass', 'Psychic'], "generation": 1},
    "Cubone": {"id": 104, "types": ['Ground'], "generation": 1},
    "Marowak": {"id": 105, "types": ['Ground'], "generation": 1},
    "Hitmonlee": {"id": 106, "types": ['Fighting'], "generation": 1},
    "Hitmonchan": {"id": 107, "types": ['Fighting'], "generation": 1},
    "Lickitung": {"id": 108, "types": ['Normal'], "generation": 1},
    "Koffing": {"id": 109, "types": ['Poison'], "generation": 1},
    "Weezing": {"id": 110, "types": ['Poison'], "generation": 1},
    "Rhyhorn": {"id": 111, "types": ['Ground', 'Rock'], "generation": 1},
    "Rhydon": {"id": 112, "types": ['Ground', 'Rock'], "generation": 1},
    "Chansey": {"id": 113, "types": ['Normal'], "generation": 1},
    "Tangela": {"id": 114, "types": ['Grass'], "generation": 1},
    "Kangaskhan": {"id": 115, "types": ['Normal'], "generation": 1},
    "Horsea": {"id": 116, "types": ['Water'], "generation": 1},
    "Seadra": {"id": 117, "types": ['Water'], "generation": 1},
    "Goldeen": {"id": 118, "types": ['Water'], "generation": 1},
    "Seaking": {"id": 119, "types": ['Water'], "generation": 1},
    "Staryu": {"id": 120, "types": ['Water'], "generation": 1},
    "Starmie": {"id": 121, "types": ['Water', 'Psychic'], "generation": 1},
    "Mr. Mime": {"id": 122, "types": ['Psychic', 'Fairy'], "generation": 1},
    "Scyther": {"id": 123, "types": ['Bug', 'Flying'], "generation": 1},
    "Jynx": {"id": 124, "types": ['Ice', 'Psychic'], "generation": 1},
    "Electabuzz": {"id": 125, "types": ['Electric'], "generation": 1},
    "Magmar": {"id": 126, "types": ['Fire'], "generation": 1},
    "Pinsir": {"id": 127, "types": ['Bug'], "generation": 1},
    "Tauros": {"id": 128, "types": ['Normal'], "generation": 1},
    "Magikarp": {"id": 129, "types": ['Water'], "generation": 1},
    "Gyarados": {"id": 130, "types": ['Water', 'Flying'], "generation": 1},
    "Lapras": {"id": 131, "types": ['Water', 'Ice'], "generation": 1},
    "Ditto": {"id": 132, "types": ['Normal'], "generation": 1},
    "Eevee": {"id": 133, "types": ['Normal'], "generation": 1},
    "Vaporeon": {"id": 134, "types": ['Water'], "generation": 1},
    "Jolteon": {"id": 135, "types": ['Electric'], "generation": 1},
    "Flareon": {"id": 136, "types": ['Fire'], "generation": 1},
    "Porygon": {"id": 137, "types": ['Normal'], "generation": 1},
    "Omanyte": {"id": 138, "types": ['Rock', 'Water'], "generation": 1},
    "Omastar": {"id": 139, "types": ['Rock', 'Water'], "generation": 1},
    "Kabuto": {"id": 140, "types": ['Rock', 'Water'], "generation": 1},
    "Kabutops": {"id": 141, "types": ['Rock', 'Water'], "generation": 1},
    "Aerodactyl": {"id": 142, "types": ['Rock', 'Flying'], "generation": 1},
    "Snorlax": {"id": 143, "types": ['Normal'], "generation": 1},
    "Articuno": {"id": 144, "types": ['Ice', 'Flying'], "generation": 1},
    "Zapdos": {"id": 145, "types": ['Electric', 'Flying'], "generation": 1},
    "Moltres": {"id": 146, "types": ['Fire', 'Flying'], "generation": 1},
    "Dratini": {"id": 147, "types": ['Dragon'], "generation": 1},
    "Dragonair": {"id": 148, "types": ['Dragon'], "generation": 1},
    "Dragonite": {"id": 149, "types": ['Dragon', 'Flying'], "generation": 1},
    "Mewtwo": {"id": 150, "types": ['Psychic'], "generation": 1},
    "Mew": {"id": 151, "types": ['Psychic'], "generation": 1},
    "Chikorita": {"id": 152, "types": ['Grass'], "generation": 2},
    "Bayleef": {"id": 153, "types": ['Grass'], "generation": 2},
    "Meganium": {"id": 154, "types": ['Grass'], "generation": 2},
    "Cyndaquil": {"id": 155, "types": ['Fire'], "generation": 2},
    "Quilava": {"id": 156, "types": ['Fire'], "generation": 2},
    "Typhlosion": {"id": 157, "types": ['Fire'], "generation": 2},
    "Totodile": {"id": 158, "types": ['Water'], "generation": 2},
    "Croconaw": {"id": 159, "types": ['Water'], "generation": 2},
    "Feraligatr": {"id": 160, "types": ['Water'], "generation": 2},
    "Sentret": {"id": 161, "types": ['Normal'], "generation": 2},
    "Furret": {"id": 162, "types": ['Normal'], "generation": 2},
    "Hoothoot": {"id": 163, "types": ['Normal', 'Flying'], "generation": 2},
    "Noctowl": {"id": 164, "types": ['Normal', 'Flying'], "generation": 2},
    "Ledyba": {"id": 165, "types": ['Bug', 'Flying'], "generation": 2},
    "Ledian": {"id": 166, "types": ['Bug', 'Flying'], "generation": 2},
    "Spinarak": {"id": 167, "types": ['Bug', 'Poison'], "generation": 2},
    "Ariados": {"id": 168, "types": ['Bug', 'Poison'], "generation": 2},
    "Crobat": {"id": 169, "types": ['Poison', 'Flying'], "generation": 2},
    "Chinchou": {"id": 170, "types": ['Water', 'Electric'], "generation": 2},
    "Lanturn": {"id": 171, "types": ['Water', 'Electric'], "generation": 2},
    "Pichu": {"id": 172, "types": ['Electric'], "generation": 2},
    "Cleffa": {"id": 173, "types": ['Fairy'], "generation": 2},
    "Igglybuff": {"id": 174, "types": ['Normal', 'Fairy'], "generation": 2},
    "Togepi": {"id": 175, "types": ['Fairy'], "generation": 2},
    "Togetic": {"id": 176, "types": ['Fairy', 'Flying'], "generation": 2},
    "Natu": {"id": 177, "types": ['Psychic', 'Flying'], "generation": 2},
    "Xatu": {"id": 178, "types": ['Psychic', 'Flying'], "generation": 2},
    "Mareep": {"id": 179, "types": ['Electric'], "generation": 2},
    "Flaaffy": {"id": 180, "types": ['Electric'], "generation": 2},
    "Ampharos": {"id": 181, "types": ['Electric'], "generation": 2},
    "Bellossom": {"id": 182, "types": ['Grass'], "generation": 2},
    "Marill": {"id": 183, "types": ['Water', 'Fairy'], "generation": 2},
    "Azumarill": {"id": 184, "types": ['Water', 'Fairy'], "generation": 2},
    "Sudowoodo": {"id": 185, "types": ['Rock'], "generation": 2},
    "Politoed": {"id": 186, "types": ['Water'], "generation": 2},
    "Hoppip": {"id": 187, "types": ['Grass', 'Flying'], "generation": 2},
    "Skiploom": {"id": 188, "types": ['Grass', 'Flying'], "generation": 2},
    "Jumpluff": {"id": 189, "types": ['Grass', 'Flying'], "generation": 2},
    "Aipom": {"id": 190, "types": ['Normal'], "generation": 2},
    "Sunkern": {"id": 191, "types": ['Grass'], "generation": 2},
    "Sunflora": {"id": 192, "types": ['Grass'], "generation": 2},
    "Yanma": {"id": 193, "types": ['Bug', 'Flying'], "generation": 2},
    "Wooper": {"id": 194, "types": ['Water', 'Ground'], "generation": 2},
    "Quagsire": {"id": 195, "types": ['Water', 'Ground'], "generation": 2},
    "Espeon": {"id": 196, "types": ['Psychic'], "generation": 2},
    "Umbreon": {"id": 197, "types": ['Dark'], "generation": 2},
    "Murkrow": {"id": 198, "types": ['Dark', 'Flying'], "generation": 2},
    "Slowking": {"id": 199, "types": ['Water', 'Psychic'], "generation": 2},
    "Misdreavus": {"id": 200, "types": ['Ghost'], "generation": 2},
    "Unown": {"id": 201, "types": ['Psychic'], "generation": 2},
    "Wobbuffet": {"id": 202, "types": ['Psychic'], "generation": 2},
    "Girafarig": {"id": 203, "types": ['Normal', 'Psychic'], "generation": 2},
    "Pineco": {"id": 204, "types": ['Bug'], "generation": 2},
    "Forretress": {"id": 205, "types": ['Bug', 'Steel'], "generation": 2},
    "Dunsparce": {"id": 206, "types": ['Normal'], "generation": 2},
    "Gligar": {"id": 207, "types": ['Ground', 'Flying'], "generation": 2},
    "Steelix": {"id": 208, "types": ['Steel', 'Ground'], "generation": 2},
    "Snubbull": {"id": 209, "types": ['Fairy'], "generation": 2},
    "Granbull": {"id": 210, "types": ['Fairy'], "generation": 2},
    "Qwilfish": {"id": 211, "types": ['Water', 'Poison'], "generation": 2},
    "Scizor": {"id": 212, "types": ['Bug', 'Steel'], "generation": 2},
    "Shuckle": {"id": 213, "types": ['Bug', 'Rock'], "generation": 2},
    "Heracross": {"id": 214, "types": ['Bug', 'Fighting'], "generation": 2},
    "Sneasel": {"id": 215, "types": ['Dark', 'Ice'], "generation": 2},
    "Teddiursa": {"id": 216, "types": ['Normal'], "generation": 2},
    "Ursaring": {"id": 217, "types": ['Normal'], "generation": 2},
    "Slugma": {"id": 218, "types": ['Fire'], "generation": 2},
    "Magcargo": {"id": 219, "types": ['Fire', 'Rock'], "generation": 2},
    "Swinub": {"id": 220, "types": ['Ice', 'Ground'], "generation": 2},
    "Piloswine": {"id": 221, "types": ['Ice', 'Ground'], "generation": 2},
    "Corsola": {"id": 222, "types": ['Water', 'Rock'], "generation": 2},
    "Remoraid": {"id": 223, "types": ['Water'], "generation": 2},
    "Octillery": {"id": 224, "types": ['Water'], "generation": 2},
    "Delibird": {"id": 225, "types": ['Ice', 'Flying'], "generation": 2},
    "Mantine": {"id": 226, "types": ['Water', 'Flying'], "generation": 2},
    "Skarmory": {"id": 227, "types": ['Steel', 'Flying'], "generation": 2},
    "Houndour": {"id": 228, "types": ['Dark', 'Fire'], "generation": 2},
    "Houndoom": {"id": 229, "types": ['Dark', 'Fire'], "generation": 2},
    "Kingdra": {"id": 230, "types": ['Water', 'Dragon'], "generation": 2},
    "Phanpy": {"id": 231, "types": ['Ground'], "generation": 2},
    "Donphan": {"id": 232, "types": ['Ground'], "generation": 2},
    "Porygon2": {"id": 233, "types": ['Normal'], "generation": 2},
    "Stantler": {"id": 234, "types": ['Normal'], "generation": 2},
    "Smeargle": {"id": 235, "types": ['Normal'], "generation": 2},
    "Tyrogue": {"id": 236, "types": ['Fighting'], "generation": 2},
    "Hitmontop": {"id": 237, "types": ['Fighting'], "generation": 2},
    "Smoochum": {"id": 238, "types": ['Ice', 'Psychic'], "generation": 2},
    "Elekid": {"id": 239, "types": ['Electric'], "generation": 2},
    "Magby": {"id": 240, "types": ['Fire'], "generation": 2},
    "Miltank": {"id": 241, "types": ['Normal'], "generation": 2},
    "Blissey": {"id": 242, "types": ['Normal'], "generation": 2},
    "Raikou": {"id": 243, "types": ['Electric'], "generation": 2},
    "Entei": {"id": 244, "types": ['Fire'], "generation": 2},
    "Suicune": {"id": 245, "types": ['Water'], "generation": 2},
    "Larvitar": {"id": 246, "types": ['Rock', 'Ground'], "generation": 2},
    "Pupitar": {"id": 247, "types": ['Rock', 'Ground'], "generation": 2},
    "Tyranitar": {"id": 248, "types": ['Rock', 'Dark'], "generation": 2},
    "Lugia": {"id": 249, "types": ['Psychic', 'Flying'], "generation": 2},
    "Ho-Oh": {"id": 250, "types": ['Fire', 'Flying'], "generation": 2},
    "Celebi": {"id": 251, "types": ['Psychic', 'Grass'], "generation": 2},
    "Treecko": {"id": 252, "types": ['Grass'], "generation": 3},
    "Grovyle": {"id": 253, "types": ['Grass'], "generation": 3},
    "Sceptile": {"id": 254, "types": ['Grass'], "generation": 3},
    "Torchic": {"id": 255, "types": ['Fire'], "generation": 3},
    "Combusken": {"id": 256, "types": ['Fire', 'Fighting'], "generation": 3},
    "Blaziken": {"id": 257, "types": ['Fire', 'Fighting'], "generation": 3},
    "Mudkip": {"id": 258, "types": ['Water'], "generation": 3},
    "Marshtomp": {"id": 259, "types": ['Water', 'Ground'], "generation": 3},
    "Swampert": {"id": 260, "types": ['Water', 'Ground'], "generation": 3},
    "Poochyena": {"id": 261, "types": ['Dark'], "generation": 3},
    "Mightyena": {"id": 262, "types": ['Dark'], "generation": 3},
    "Zigzagoon": {"id": 263, "types": ['Normal'], "generation": 3},
    "Linoone": {"id": 264, "types": ['Normal'], "generation": 3},
    "Wurmple": {"id": 265, "types": ['Bug'], "generation": 3},
    "Silcoon": {"id": 266, "types": ['Bug'], "generation": 3},
    "Beautifly": {"id": 267, "types": ['Bug', 'Flying'], "generation": 3},
    "Cascoon": {"id": 268, "types": ['Bug'], "generation": 3},
    "Dustox": {"id": 269, "types": ['Bug', 'Poison'], "generation": 3},
    "Lotad": {"id": 270, "types": ['Water', 'Grass'], "generation": 3},
    "Lombre": {"id": 271, "types": ['Water', 'Grass'], "generation": 3},
    "Ludicolo": {"id": 272, "types": ['Water', 'Grass'], "generation": 3},
    "Seedot": {"id": 273, "types": ['Grass'], "generation": 3},
    "Nuzleaf": {"id": 274, "types": ['Grass', 'Dark'], "generation": 3},
    "Shiftry": {"id": 275, "types": ['Grass', 'Dark'], "generation": 3},
    "Taillow": {"id": 276, "types": ['Normal', 'Flying'], "generation": 3},
    "Swellow": {"id": 277, "types": ['Normal', 'Flying'], "generation": 3},
    "Wingull": {"id": 278, "types": ['Water', 'Flying'], "generation": 3},
    "Pelipper": {"id": 279, "types": ['Water', 'Flying'], "generation": 3},
    "Ralts": {"id": 280, "types": ['Psychic', 'Fairy'], "generation": 3},
    "Kirlia": {"id": 281, "types": ['Psychic', 'Fairy'], "generation": 3},
    "Gardevoir": {"id": 282, "types": ['Psychic', 'Fairy'], "generation": 3},
    "Surskit": {"id": 283, "types": ['Bug', 'Water'], "generation": 3},
    "Masquerain": {"id": 284, "types": ['Bug', 'Flying'], "generation": 3},
    "Shroomish": {"id": 285, "types": ['Grass'], "generation": 3},
    "Breloom": {"id": 286, "types": ['Grass', 'Fighting'], "generation": 3},
    "Slakoth": {"id": 287, "types": ['Normal'], "generation": 3},
    "Vigoroth": {"id": 288, "types": ['Normal'], "generation": 3},
    "Slaking": {"id": 289, "types": ['Normal'], "generation": 3},
    "Nincada": {"id": 290, "types": ['Bug', 'Ground'], "generation": 3},
    "Ninjask": {"id": 291, "types": ['Bug', 'Flying'], "generation": 3},
    "Shedinja": {"id": 292, "types": ['Bug', 'Ghost'], "generation": 3},
    "Whismur": {"id": 293, "types": ['Normal'], "generation": 3},
    "Loudred": {"id": 294, "types": ['Normal'], "generation": 3},
    "Exploud": {"id": 295, "types": ['Normal'], "generation": 3},
    "Makuhita": {"id": 296, "types": ['Fighting'], "generation": 3},
    "Hariyama": {"id": 297, "types": ['Fighting'], "generation": 3},
    "Azurill": {"id": 298, "types": ['Normal', 'Fairy'], "generation": 3},
    "Nosepass": {"id": 299, "types": ['Rock'], "generation": 3},
    "Skitty": {"id": 300, "types": ['Normal'], "generation": 3},
    "Delcatty": {"id": 301, "types": ['Normal'], "generation": 3},
    "Sableye": {"id": 302, "types": ['Dark', 'Ghost'], "generation": 3},
    "Mawile": {"id": 303, "types": ['Steel', 'Fairy'], "generation": 3},
    "Aron": {"id": 304, "types": ['Steel', 'Rock'], "generation": 3},
    "Lairon": {"id": 305, "types": ['Steel', 'Rock'], "generation": 3},
    "Aggron": {"id": 306, "types": ['Steel', 'Rock'], "generation": 3},
    "Meditite": {"id": 307, "types": ['Fighting', 'Psychic'], "generation": 3},
    "Medicham": {"id": 308, "types": ['Fighting', 'Psychic'], "generation": 3},
    "Electrike": {"id": 309, "types": ['Electric'], "generation": 3},
    "Manectric": {"id": 310, "types": ['Electric'], "generation": 3},
    "Plusle": {"id": 311, "types": ['Electric'], "generation": 3},
    "Minun": {"id": 312, "types": ['Electric'], "generation": 3},
    "Volbeat": {"id": 313, "types": ['Bug'], "generation": 3},
    "Illumise": {"id": 314, "types": ['Bug'], "generation": 3},
    "Roselia": {"id": 315, "types": ['Grass', 'Poison'], "generation": 3},
    "Gulpin": {"id": 316, "types": ['Poison'], "generation": 3},
    "Swalot": {"id": 317, "types": ['Poison'], "generation": 3},
    "Carvanha": {"id": 318, "types": ['Water', 'Dark'], "generation": 3},
    "Sharpedo": {"id": 319, "types": ['Water', 'Dark'], "generation": 3},
    "Wailmer": {"id": 320, "types": ['Water'], "generation": 3},
    "Wailord": {"id": 321, "types": ['Water'], "generation": 3},
    "Numel": {"id": 322, "types": ['Fire', 'Ground'], "generation": 3},
    "Camerupt": {"id": 323, "types": ['Fire', 'Ground'], "generation": 3},
    "Torkoal": {"id": 324, "types": ['Fire'], "generation": 3},
    "Spoink": {"id": 325, "types": ['Psychic'], "generation": 3},
    "Grumpig": {"id": 326, "types": ['Psychic'], "generation": 3},
    "Spinda": {"id": 327, "types": ['Normal'], "generation": 3},
    "Trapinch": {"id": 328, "types": ['Ground'], "generation": 3},
    "Vibrava": {"id": 329, "types": ['Ground', 'Dragon'], "generation": 3},
    "Flygon": {"id": 330, "types": ['Ground', 'Dragon'], "generation": 3},
    "Cacnea": {"id": 331, "types": ['Grass'], "generation": 3},
    "Cacturne": {"id": 332, "types": ['Grass', 'Dark'], "generation": 3},
    "Swablu": {"id": 333, "types": ['Normal', 'Flying'], "generation": 3},
    "Altaria": {"id": 334, "types": ['Dragon', 'Flying'], "generation": 3},
    "Zangoose": {"id": 335, "types": ['Normal'], "generation": 3},
    "Seviper": {"id": 336, "types": ['Poison'], "generation": 3},
    "Lunatone": {"id": 337, "types": ['Rock', 'Psychic'], "generation": 3},
    "Solrock": {"id": 338, "types": ['Rock', 'Psychic'], "generation": 3},
    "Barboach": {"id": 339, "types": ['Water', 'Ground'], "generation": 3},
    "Whiscash": {"id": 340, "types": ['Water', 'Ground'], "generation": 3},
    "Corphish": {"id": 341, "types": ['Water'], "generation": 3},
    "Crawdaunt": {"id": 342, "types": ['Water', 'Dark'], "generation": 3},
    "Baltoy": {"id": 343, "types": ['Ground', 'Psychic'], "generation": 3},
    "Claydol": {"id": 344, "types": ['Ground', 'Psychic'], "generation": 3},
    "Lileep": {"id": 345, "types": ['Rock', 'Grass'], "generation": 3},
    "Cradily": {"id": 346, "types": ['Rock', 'Grass'], "generation": 3},
    "Anorith": {"id": 347, "types": ['Rock', 'Bug'], "generation": 3},
    "Armaldo": {"id": 348, "types": ['Rock', 'Bug'], "generation": 3},
    "Feebas": {"id": 349, "types": ['Water'], "generation": 3},
    "Milotic": {"id": 350, "types": ['Water'], "generation": 3},
    "Castform": {"id": 351, "types": ['Normal'], "generation": 3},
    "Kecleon": {"id": 352, "types": ['Normal'], "generation": 3},
    "Shuppet": {"id": 353, "types": ['Ghost'], "generation": 3},
    "Banette": {"id": 354, "types": ['Ghost'], "generation": 3},
    "Duskull": {"id": 355, "types": ['Ghost'], "generation": 3},
    "Dusclops": {"id": 356, "types": ['Ghost'], "generation": 3},
    "Tropius": {"id": 357, "types": ['Grass', 'Flying'], "generation": 3},
    "Chimecho": {"id": 358, "types": ['Psychic'], "generation": 3},
    "Absol": {"id": 359, "types": ['Dark'], "generation": 3},
    "Wynaut": {"id": 360, "types": ['Psychic'], "generation": 3},
    "Snorunt": {"id": 361, "types": ['Ice'], "generation": 3},
    "Glalie": {"id": 362, "types": ['Ice'], "generation": 3},
    "Spheal": {"id": 363, "types": ['Ice', 'Water'], "generation": 3},
    "Sealeo": {"id": 364, "types": ['Ice', 'Water'], "generation": 3},
    "Walrein": {"id": 365, "types": ['Ice', 'Water'], "generation": 3},
    "Clamperl": {"id": 366, "types": ['Water'], "generation": 3},
    "Huntail": {"id": 367, "types": ['Water'], "generation": 3},
    "Gorebyss": {"id": 368, "types": ['Water'], "generation": 3},
    "Relicanth": {"id": 369, "types": ['Water', 'Rock'], "generation": 3},
    "Luvdisc": {"id": 370, "types": ['Water'], "generation": 3},
    "Bagon": {"id": 371, "types": ['Dragon'], "generation": 3},
    "Shelgon": {"id": 372, "types": ['Dragon'], "generation": 3},
    "Salamence": {"id": 373, "types": ['Dragon', 'Flying'], "generation": 3},
    "Beldum": {"id": 374, "types": ['Steel', 'Psychic'], "generation": 3},
    "Metang": {"id": 375, "types": ['Steel', 'Psychic'], "generation": 3},
    "Metagross": {"id": 376, "types": ['Steel', 'Psychic'], "generation": 3},
    "Regirock": {"id": 377, "types": ['Rock'], "generation": 3},
    "Regice": {"id": 378, "types": ['Ice'], "generation": 3},
    "Registeel": {"id": 379, "types": ['Steel'], "generation": 3},
    "Latias": {"id": 380, "types": ['Dragon', 'Psychic'], "generation": 3},
    "Latios": {"id": 381, "types": ['Dragon', 'Psychic'], "generation": 3},
    "Kyogre": {"id": 382, "types": ['Water'], "generation": 3},
    "Groudon": {"id": 383, "types": ['Ground'], "generation": 3},
    "Rayquaza": {"id": 384, "types": ['Dragon', 'Flying'], "generation": 3},
    "Jirachi": {"id": 385, "types": ['Steel', 'Psychic'], "generation": 3},
    "Deoxys": {"id": 386, "types": ['Psychic'], "generation": 3},
    "Turtwig": {"id": 387, "types": ['Grass'], "generation": 4},
    "Grotle": {"id": 388, "types": ['Grass'], "generation": 4},
    "Torterra": {"id": 389, "types": ['Grass', 'Ground'], "generation": 4},
    "Chimchar": {"id": 390, "types": ['Fire'], "generation": 4},
    "Monferno": {"id": 391, "types": ['Fire', 'Fighting'], "generation": 4},
    "Infernape": {"id": 392, "types": ['Fire', 'Fighting'], "generation": 4},
    "Piplup": {"id": 393, "types": ['Water'], "generation": 4},
    "Prinplup": {"id": 394, "types": ['Water'], "generation": 4},
    "Empoleon": {"id": 395, "types": ['Water', 'Steel'], "generation": 4},
    "Starly": {"id": 396, "types": ['Normal', 'Flying'], "generation": 4},
    "Staravia": {"id": 397, "types": ['Normal', 'Flying'], "generation": 4},
    "Staraptor": {"id": 398, "types": ['Normal', 'Flying'], "generation": 4},
    "Bidoof": {"id": 399, "types": ['Normal'], "generation": 4},
    "Bibarel": {"id": 400, "types": ['Normal', 'Water'], "generation": 4},
    "Kricketot": {"id": 401, "types": ['Bug'], "generation": 4},
    "Kricketune": {"id": 402, "types": ['Bug'], "generation": 4},
    "Shinx": {"id": 403, "types": ['Electric'], "generation": 4},
    "Luxio": {"id": 404, "types": ['Electric'], "generation": 4},
    "Luxray": {"id": 405, "types": ['Electric'], "generation": 4},
    "Budew": {"id": 406, "types": ['Grass', 'Poison'], "generation": 4},
    "Roserade": {"id": 407, "types": ['Grass', 'Poison'], "generation": 4},
    "Cranidos": {"id": 408, "types": ['Rock'], "generation": 4},
    "Rampardos": {"id": 409, "types": ['Rock'], "generation": 4},
    "Shieldon": {"id": 410, "types": ['Rock', 'Steel'], "generation": 4},
    "Bastiodon": {"id": 411, "types": ['Rock', 'Steel'], "generation": 4},
    "Burmy": {"id": 412, "types": ['Bug'], "generation": 4},
    "Wormadam": {"id": 413, "types": ['Bug', 'Grass'], "generation": 4},
    "Mothim": {"id": 414, "types": ['Bug', 'Flying'], "generation": 4},
    "Combee": {"id": 415, "types": ['Bug', 'Flying'], "generation": 4},
    "Vespiquen": {"id": 416, "types": ['Bug', 'Flying'], "generation": 4},
    "Pachirisu": {"id": 417, "types": ['Electric'], "generation": 4},
    "Buizel": {"id": 418, "types": ['Water'], "generation": 4},
    "Floatzel": {"id": 419, "types": ['Water'], "generation": 4},
    "Cherubi": {"id": 420, "types": ['Grass'], "generation": 4},
    "Cherrim": {"id": 421, "types": ['Grass'], "generation": 4},
    "Shellos": {"id": 422, "types": ['Water'], "generation": 4},
    "Gastrodon": {"id": 423, "types": ['Water', 'Ground'], "generation": 4},
    "Ambipom": {"id": 424, "types": ['Normal'], "generation": 4},
    "Drifloon": {"id": 425, "types": ['Ghost', 'Flying'], "generation": 4},
    "Drifblim": {"id": 426, "types": ['Ghost', 'Flying'], "generation": 4},
    "Buneary": {"id": 427, "types": ['Normal'], "generation": 4},
    "Lopunny": {"id": 428, "types": ['Normal'], "generation": 4},
    "Mismagius": {"id": 429, "types": ['Ghost'], "generation": 4},
    "Honchkrow": {"id": 430, "types": ['Dark', 'Flying'], "generation": 4},
    "Glameow": {"id": 431, "types": ['Normal'], "generation": 4},
    "Purugly": {"id": 432, "types": ['Normal'], "generation": 4},
    "Chingling": {"id": 433, "types": ['Psychic'], "generation": 4},
    "Stunky": {"id": 434, "types": ['Poison', 'Dark'], "generation": 4},
    "Skuntank": {"id": 435, "types": ['Poison', 'Dark'], "generation": 4},
    "Bronzor": {"id": 436, "types": ['Steel', 'Psychic'], "generation": 4},
    "Bronzong": {"id": 437, "types": ['Steel', 'Psychic'], "generation": 4},
    "Bonsly": {"id": 438, "types": ['Rock'], "generation": 4},
    "Mime Jr.": {"id": 439, "types": ['Psychic', 'Fairy'], "generation": 4},
    "Happiny": {"id": 440, "types": ['Normal'], "generation": 4},
    "Chatot": {"id": 441, "types": ['Normal', 'Flying'], "generation": 4},
    "Spiritomb": {"id": 442, "types": ['Ghost', 'Dark'], "generation": 4},
    "Gible": {"id": 443, "types": ['Dragon', 'Ground'], "generation": 4},
    "Gabite": {"id": 444, "types": ['Dragon', 'Ground'], "generation": 4},
    "Garchomp": {"id": 445, "types": ['Dragon', 'Ground'], "generation": 4},
    "Munchlax": {"id": 446, "types": ['Normal'], "generation": 4},
    "Riolu": {"id": 447, "types": ['Fighting'], "generation": 4},
    "Lucario": {"id": 448, "types": ['Fighting', 'Steel'], "generation": 4},
    "Hippopotas": {"id": 449, "types": ['Ground'], "generation": 4},
    "Hippowdon": {"id": 450, "types": ['Ground'], "generation": 4},
    "Skorupi": {"id": 451, "types": ['Poison', 'Bug'], "generation": 4},
    "Drapion": {"id": 452, "types": ['Poison', 'Dark'], "generation": 4},
    "Croagunk": {"id": 453, "types": ['Poison', 'Fighting'], "generation": 4},
    "Toxicroak": {"id": 454, "types": ['Poison', 'Fighting'], "generation": 4},
    "Carnivine": {"id": 455, "types": ['Grass'], "generation": 4},
    "Finneon": {"id": 456, "types": ['Water'], "generation": 4},
    "Lumineon": {"id": 457, "types": ['Water'], "generation": 4},
    "Mantyke": {"id": 458, "types": ['Water', 'Flying'], "generation": 4},
    "Snover": {"id": 459, "types": ['Grass', 'Ice'], "generation": 4},
    "Abomasnow": {"id": 460, "types": ['Grass', 'Ice'], "generation": 4},
    "Weavile": {"id": 461, "types": ['Dark', 'Ice'], "generation": 4},
    "Magnezone": {"id": 462, "types": ['Electric', 'Steel'], "generation": 4},
    "Lickilicky": {"id": 463, "types": ['Normal'], "generation": 4},
    "Rhyperior": {"id": 464, "types": ['Ground', 'Rock'], "generation": 4},
    "Tangrowth": {"id": 465, "types": ['Grass'], "generation": 4},
    "Electivire": {"id": 466, "types": ['Electric'], "generation": 4},
    "Magmortar": {"id": 467, "types": ['Fire'], "generation": 4},
    "Togekiss": {"id": 468, "types": ['Fairy', 'Flying'], "generation": 4},
    "Yanmega": {"id": 469, "types": ['Bug', 'Flying'], "generation": 4},
    "Leafeon": {"id": 470, "types": ['Grass'], "generation": 4},
    "Glaceon": {"id": 471, "types": ['Ice'], "generation": 4},
    "Gliscor": {"id": 472, "types": ['Ground', 'Flying'], "generation": 4},
    "Mamoswine": {"id": 473, "types": ['Ice', 'Ground'], "generation": 4},
    "Porygon-Z": {"id": 474, "types": ['Normal'], "generation": 4},
    "Gallade": {"id": 475, "types": ['Psychic', 'Fighting'], "generation": 4},
    "Probopass": {"id": 476, "types": ['Rock', 'Steel'], "generation": 4},
    "Dusknoir": {"id": 477, "types": ['Ghost'], "generation": 4},
    "Froslass": {"id": 478, "types": ['Ice', 'Ghost'], "generation": 4},
    "Rotom": {"id": 479, "types": ['Electric', 'Ghost'], "generation": 4},
    "Uxie": {"id": 480, "types": ['Psychic'], "generation": 4},
    "Mesprit": {"id": 481, "types": ['Psychic'], "generation": 4},
    "Azelf": {"id": 482, "types": ['Psychic'], "generation": 4},
    "Dialga": {"id": 483, "types": ['Steel', 'Dragon'], "generation": 4},
    "Palkia": {"id": 484, "types": ['Water', 'Dragon'], "generation": 4},
    "Heatran": {"id": 485, "types": ['Fire', 'Steel'], "generation": 4},
    "Regigigas": {"id": 486, "types": ['Normal'], "generation": 4},
    "Giratina": {"id": 487, "types": ['Ghost', 'Dragon'], "generation": 4},
    "Cresselia": {"id": 488, "types": ['Psychic'], "generation": 4},
    "Phione": {"id": 489, "types": ['Water'], "generation": 4},
    "Manaphy": {"id": 490, "types": ['Water'], "generation": 4},
    "Darkrai": {"id": 491, "types": ['Dark'], "generation": 4},
    "Shaymin": {"id": 492, "types": ['Grass'], "generation": 4},
    "Arceus": {"id": 493, "types": ['Normal'], "generation": 4},
    "Victini": {"id": 494, "types": ['Psychic', 'Fire'], "generation": 5},
    "Snivy": {"id": 495, "types": ['Grass'], "generation": 5},
    "Servine": {"id": 496, "types": ['Grass'], "generation": 5},
    "Serperior": {"id": 497, "types": ['Grass'], "generation": 5},
    "Tepig": {"id": 498, "types": ['Fire'], "generation": 5},
    "Pignite": {"id": 499, "types": ['Fire', 'Fighting'], "generation": 5},
    "Emboar": {"id": 500, "types": ['Fire', 'Fighting'], "generation": 5},
    "Oshawott": {"id": 501, "types": ['Water'], "generation": 5},
    "Dewott": {"id": 502, "types": ['Water'], "generation": 5},
    "Samurott": {"id": 503, "types": ['Water'], "generation": 5},
    "Patrat": {"id": 504, "types": ['Normal'], "generation": 5},
    "Watchog": {"id": 505, "types": ['Normal'], "generation": 5},
    "Lillipup": {"id": 506, "types": ['Normal'], "generation": 5},
    "Herdier": {"id": 507, "types": ['Normal'], "generation": 5},
    "Stoutland": {"id": 508, "types": ['Normal'], "generation": 5},
    "Purrloin": {"id": 509, "types": ['Dark'], "generation": 5},
    "Liepard": {"id": 510, "types": ['Dark'], "generation": 5},
    "Pansage": {"id": 511, "types": ['Grass'], "generation": 5},
    "Simisage": {"id": 512, "types": ['Grass'], "generation": 5},
    "Pansear": {"id": 513, "types": ['Fire'], "generation": 5},
    "Simisear": {"id": 514, "types": ['Fire'], "generation": 5},
    "Panpour": {"id": 515, "types": ['Water'], "generation": 5},
    "Simipour": {"id": 516, "types": ['Water'], "generation": 5},
    "Munna": {"id": 517, "types": ['Psychic'], "generation": 5},
    "Musharna": {"id": 518, "types": ['Psychic'], "generation": 5},
    "Pidove": {"id": 519, "types": ['Normal', 'Flying'], "generation": 5},
    "Tranquill": {"id": 520, "types": ['Normal', 'Flying'], "generation": 5},
    "Unfezant": {"id": 521, "types": ['Normal', 'Flying'], "generation": 5},
    "Blitzle": {"id": 522, "types": ['Electric'], "generation": 5},
    "Zebstrika": {"id": 523, "types": ['Electric'], "generation": 5},
    "Roggenrola": {"id": 524, "types": ['Rock'], "generation": 5},
    "Boldore": {"id": 525, "types": ['Rock'], "generation": 5},
    "Gigalith": {"id": 526, "types": ['Rock'], "generation": 5},
    "Woobat": {"id": 527, "types": ['Psychic', 'Flying'], "generation": 5},
    "Swoobat": {"id": 528, "types": ['Psychic', 'Flying'], "generation": 5},
    "Drilbur": {"id": 529, "types": ['Ground'], "generation": 5},
    "Excadrill": {"id": 530, "types": ['Ground', 'Steel'], "generation": 5},
    "Audino": {"id": 531, "types": ['Normal'], "generation": 5},
    "Timburr": {"id": 532, "types": ['Fighting'], "generation": 5},
    "Gurdurr": {"id": 533, "types": ['Fighting'], "generation": 5},
    "Conkeldurr": {"id": 534, "types": ['Fighting'], "generation": 5},
    "Tympole": {"id": 535, "types": ['Water'], "generation": 5},
    "Palpitoad": {"id": 536, "types": ['Water', 'Ground'], "generation": 5},
    "Seismitoad": {"id": 537, "types": ['Water', 'Ground'], "generation": 5},
    "Throh": {"id": 538, "types": ['Fighting'], "generation": 5},
    "Sawk": {"id": 539, "types": ['Fighting'], "generation": 5},
    "Sewaddle": {"id": 540, "types": ['Bug', 'Grass'], "generation": 5},
    "Swadloon": {"id": 541, "types": ['Bug', 'Grass'], "generation": 5},
    "Leavanny": {"id": 542, "types": ['Bug', 'Grass'], "generation": 5},
    "Venipede": {"id": 543, "types": ['Bug', 'Poison'], "generation": 5},
    "Whirlipede": {"id": 544, "types": ['Bug', 'Poison'], "generation": 5},
    "Scolipede": {"id": 545, "types": ['Bug', 'Poison'], "generation": 5},
    "Cottonee": {"id": 546, "types": ['Grass', 'Fairy'], "generation": 5},
    "Whimsicott": {"id": 547, "types": ['Grass', 'Fairy'], "generation": 5},
    "Petilil": {"id": 548, "types": ['Grass'], "generation": 5},
    "Lilligant": {"id": 549, "types": ['Grass'], "generation": 5},
    "Basculin": {"id": 550, "types": ['Water'], "generation": 5},
    "Sandile": {"id": 551, "types": ['Ground', 'Dark'], "generation": 5},
    "Krokorok": {"id": 552, "types": ['Ground', 'Dark'], "generation": 5},
    "Krookodile": {"id": 553, "types": ['Ground', 'Dark'], "generation": 5},
    "Darumaka": {"id": 554, "types": ['Fire'], "generation": 5},
    "Darmanitan": {"id": 555, "types": ['Fire'], "generation": 5},
    "Maractus": {"id": 556, "types": ['Grass'], "generation": 5},
    "Dwebble": {"id": 557, "types": ['Bug', 'Rock'], "generation": 5},
    "Crustle": {"id": 558, "types": ['Bug', 'Rock'], "generation": 5},
    "Scraggy": {"id": 559, "types": ['Dark', 'Fighting'], "generation": 5},
    "Scrafty": {"id": 560, "types": ['Dark', 'Fighting'], "generation": 5},
    "Sigilyph": {"id": 561, "types": ['Psychic', 'Flying'], "generation": 5},
    "Yamask": {"id": 562, "types": ['Ghost'], "generation": 5},
    "Cofagrigus": {"id": 563, "types": ['Ghost'], "generation": 5},
    "Tirtouga": {"id": 564, "types": ['Water', 'Rock'], "generation": 5},
    "Carracosta": {"id": 565, "types": ['Water', 'Rock'], "generation": 5},
    "Archen": {"id": 566, "types": ['Rock', 'Flying'], "generation": 5},
    "Archeops": {"id": 567, "types": ['Rock', 'Flying'], "generation": 5},
    "Trubbish": {"id": 568, "types": ['Poison'], "generation": 5},
    "Garbodor": {"id": 569, "types": ['Poison'], "generation": 5},
    "Zorua": {"id": 570, "types": ['Dark'], "generation": 5},
    "Zoroark": {"id": 571, "types": ['Dark'], "generation": 5},
    "Minccino": {"id": 572, "types": ['Normal'], "generation": 5},
    "Cinccino": {"id": 573, "types": ['Normal'], "generation": 5},
    "Gothita": {"id": 574, "types": ['Psychic'], "generation": 5},
    "Gothorita": {"id": 575, "types": ['Psychic'], "generation": 5},
    "Gothitelle": {"id": 576, "types": ['Psychic'], "generation": 5},
    "Solosis": {"id": 577, "types": ['Psychic'], "generation": 5},
    "Duosion": {"id": 578, "types": ['Psychic'], "generation": 5},
    "Reuniclus": {"id": 579, "types": ['Psychic'], "generation": 5},
    "Ducklett": {"id": 580, "types": ['Water', 'Flying'], "generation": 5},
    "Swanna": {"id": 581, "types": ['Water', 'Flying'], "generation": 5},
    "Vanillite": {"id": 582, "types": ['Ice'], "generation": 5},
    "Vanillish": {"id": 583, "types": ['Ice'], "generation": 5},
    "Vanilluxe": {"id": 584, "types": ['Ice'], "generation": 5},
    "Deerling": {"id": 585, "types": ['Normal', 'Grass'], "generation": 5},
    "Sawsbuck": {"id": 586, "types": ['Normal', 'Grass'], "generation": 5},
    "Emolga": {"id": 587, "types": ['Electric', 'Flying'], "generation": 5},
    "Karrablast": {"id": 588, "types": ['Bug'], "generation": 5},
    "Escavalier": {"id": 589, "types": ['Bug', 'Steel'], "generation": 5},
    "Foongus": {"id": 590, "types": ['Grass', 'Poison'], "generation": 5},
    "Amoonguss": {"id": 591, "types": ['Grass', 'Poison'], "generation": 5},
    "Frillish": {"id": 592, "types": ['Water', 'Ghost'], "generation": 5},
    "Jellicent": {"id": 593, "types": ['Water', 'Ghost'], "generation": 5},
    "Alomomola": {"id": 594, "types": ['Water'], "generation": 5},
    "Joltik": {"id": 595, "types": ['Bug', 'Electric'], "generation": 5},
    "Galvantula": {"id": 596, "types": ['Bug', 'Electric'], "generation": 5},
    "Ferroseed": {"id": 597, "types": ['Grass', 'Steel'], "generation": 5},
    "Ferrothorn": {"id": 598, "types": ['Grass', 'Steel'], "generation": 5},
    "Klink": {"id": 599, "types": ['Steel'], "generation": 5},
    "Klang": {"id": 600, "types": ['Steel'], "generation": 5},
    "Klinklang": {"id": 601, "types": ['Steel'], "generation": 5},
    "Tynamo": {"id": 602, "types": ['Electric'], "generation": 5},
    "Eelektrik": {"id": 603, "types": ['Electric'], "generation": 5},
    "Eelektross": {"id": 604, "types": ['Electric'], "generation": 5},
    "Elgyem": {"id": 605, "types": ['Psychic'], "generation": 5},
    "Beheeyem": {"id": 606, "types": ['Psychic'], "generation": 5},
    "Litwick": {"id": 607, "types": ['Ghost', 'Fire'], "generation": 5},
    "Lampent": {"id": 608, "types": ['Ghost', 'Fire'], "generation": 5},
    "Chandelure": {"id": 609, "types": ['Ghost', 'Fire'], "generation": 5},
    "Axew": {"id": 610, "types": ['Dragon'], "generation": 5},
    "Fraxure": {"id": 611, "types": ['Dragon'], "generation": 5},
    "Haxorus": {"id": 612, "types": ['Dragon'], "generation": 5},
    "Cubchoo": {"id": 613, "types": ['Ice'], "generation": 5},
    "Beartic": {"id": 614, "types": ['Ice'], "generation": 5},
    "Cryogonal": {"id": 615, "types": ['Ice'], "generation": 5},
    "Shelmet": {"id": 616, "types": ['Bug'], "generation": 5},
    "Accelgor": {"id": 617, "types": ['Bug'], "generation": 5},
    "Stunfisk": {"id": 618, "types": ['Ground', 'Electric'], "generation": 5},
    "Mienfoo": {"id": 619, "types": ['Fighting'], "generation": 5},
    "Mienshao": {"id": 620, "types": ['Fighting'], "generation": 5},
    "Druddigon": {"id": 621, "types": ['Dragon'], "generation": 5},
    "Golett": {"id": 622, "types": ['Ground', 'Ghost'], "generation": 5},
    "Golurk": {"id": 623, "types": ['Ground', 'Ghost'], "generation": 5},
    "Pawniard": {"id": 624, "types": ['Dark', 'Steel'], "generation": 5},
    "Bisharp": {"id": 625, "types": ['Dark', 'Steel'], "generation": 5},
    "Bouffalant": {"id": 626, "types": ['Normal'], "generation": 5},
    "Rufflet": {"id": 627, "types": ['Normal', 'Flying'], "generation": 5},
    "Braviary": {"id": 628, "types": ['Normal', 'Flying'], "generation": 5},
    "Vullaby": {"id": 629, "types": ['Dark', 'Flying'], "generation": 5},
    "Mandibuzz": {"id": 630, "types": ['Dark', 'Flying'], "generation": 5},
    "Heatmor": {"id": 631, "types": ['Fire'], "generation": 5},
    "Durant": {"id": 632, "types": ['Bug', 'Steel'], "generation": 5},
    "Deino": {"id": 633, "types": ['Dark', 'Dragon'], "generation": 5},
    "Zweilous": {"id": 634, "types": ['Dark', 'Dragon'], "generation": 5},
    "Hydreigon": {"id": 635, "types": ['Dark', 'Dragon'], "generation": 5},
    "Larvesta": {"id": 636, "types": ['Bug', 'Fire'], "generation": 5},
    "Volcarona": {"id": 637, "types": ['Bug', 'Fire'], "generation": 5},
    "Cobalion": {"id": 638, "types": ['Steel', 'Fighting'], "generation": 5},
    "Terrakion": {"id": 639, "types": ['Rock', 'Fighting'], "generation": 5},
    "Virizion": {"id": 640, "types": ['Grass', 'Fighting'], "generation": 5},
    "Tornadus": {"id": 641, "types": ['Flying'], "generation": 5},
    "Thundurus": {"id": 642, "types": ['Electric', 'Flying'], "generation": 5},
    "Reshiram": {"id": 643, "types": ['Dragon', 'Fire'], "generation": 5},
    "Zekrom": {"id": 644, "types": ['Dragon', 'Electric'], "generation": 5},
    "Landorus": {"id": 645, "types": ['Ground', 'Flying'], "generation": 5},
    "Kyurem": {"id": 646, "types": ['Dragon', 'Ice'], "generation": 5},
    "Keldeo": {"id": 647, "types": ['Water', 'Fighting'], "generation": 5},
    "Meloetta": {"id": 648, "types": ['Normal', 'Psychic'], "generation": 5},
    "Genesect": {"id": 649, "types": ['Bug', 'Steel'], "generation": 5},
    "Chespin": {"id": 650, "types": ['Grass'], "generation": 6},
    "Quilladin": {"id": 651, "types": ['Grass'], "generation": 6},
    "Chesnaught": {"id": 652, "types": ['Grass', 'Fighting'], "generation": 6},
    "Fennekin": {"id": 653, "types": ['Fire'], "generation": 6},
    "Braixen": {"id": 654, "types": ['Fire'], "generation": 6},
    "Delphox": {"id": 655, "types": ['Fire', 'Psychic'], "generation": 6},
    "Froakie": {"id": 656, "types": ['Water'], "generation": 6},
    "Frogadier": {"id": 657, "types": ['Water'], "generation": 6},
    "Greninja": {"id": 658, "types": ['Water', 'Dark'], "generation": 6},
    "Bunnelby": {"id": 659, "types": ['Normal'], "generation": 6},
    "Diggersby": {"id": 660, "types": ['Normal', 'Ground'], "generation": 6},
    "Fletchling": {"id": 661, "types": ['Normal', 'Flying'], "generation": 6},
    "Fletchinder": {"id": 662, "types": ['Fire', 'Flying'], "generation": 6},
    "Talonflame": {"id": 663, "types": ['Fire', 'Flying'], "generation": 6},
    "Scatterbug": {"id": 664, "types": ['Bug'], "generation": 6},
    "Spewpa": {"id": 665, "types": ['Bug'], "generation": 6},
    "Vivillon": {"id": 666, "types": ['Bug', 'Flying'], "generation": 6},
    "Litleo": {"id": 667, "types": ['Fire', 'Normal'], "generation": 6},
    "Pyroar": {"id": 668, "types": ['Fire', 'Normal'], "generation": 6},
    "Flabebe": {"id": 669, "types": ['Fairy'], "generation": 6},
    "Floette": {"id": 670, "types": ['Fairy'], "generation": 6},
    "Florges": {"id": 671, "types": ['Fairy'], "generation": 6},
    "Skiddo": {"id": 672, "types": ['Grass'], "generation": 6},
    "Gogoat": {"id": 673, "types": ['Grass'], "generation": 6},
    "Pancham": {"id": 674, "types": ['Fighting'], "generation": 6},
    "Pangoro": {"id": 675, "types": ['Fighting', 'Dark'], "generation": 6},
    "Furfrou": {"id": 676, "types": ['Normal'], "generation": 6},
    "Espurr": {"id": 677, "types": ['Psychic'], "generation": 6},
    "Meowstic": {"id": 678, "types": ['Psychic'], "generation": 6},
    "Honedge": {"id": 679, "types": ['Steel', 'Ghost'], "generation": 6},
    "Doublade": {"id": 680, "types": ['Steel', 'Ghost'], "generation": 6},
    "Aegislash": {"id": 681, "types": ['Steel', 'Ghost'], "generation": 6},
    "Spritzee": {"id": 682, "types": ['Fairy'], "generation": 6},
    "Aromatisse": {"id": 683, "types": ['Fairy'], "generation": 6},
    "Swirlix": {"id": 684, "types": ['Fairy'], "generation": 6},
    "Slurpuff": {"id": 685, "types": ['Fairy'], "generation": 6},
    "Inkay": {"id": 686, "types": ['Dark', 'Psychic'], "generation": 6},
    "Malamar": {"id": 687, "types": ['Dark', 'Psychic'], "generation": 6},
    "Binacle": {"id": 688, "types": ['Rock', 'Water'], "generation": 6},
    "Barbaracle": {"id": 689, "types": ['Rock', 'Water'], "generation": 6},
    "Skrelp": {"id": 690, "types": ['Poison', 'Water'], "generation": 6},
    "Dragalge": {"id": 691, "types": ['Poison', 'Dragon'], "generation": 6},
    "Clauncher": {"id": 692, "types": ['Water'], "generation": 6},
    "Clawitzer": {"id": 693, "types": ['Water'], "generation": 6},
    "Helioptile": {"id": 694, "types": ['Electric', 'Normal'], "generation": 6},
    "Heliolisk": {"id": 695, "types": ['Electric', 'Normal'], "generation": 6},
    "Tyrunt": {"id": 696, "types": ['Rock', 'Dragon'], "generation": 6},
    "Tyrantrum": {"id": 697, "types": ['Rock', 'Dragon'], "generation": 6},
    "Amaura": {"id": 698, "types": ['Rock', 'Ice'], "generation": 6},
    "Aurorus": {"id": 699, "types": ['Rock', 'Ice'], "generation": 6},
    "Sylveon": {"id": 700, "types": ['Fairy'], "generation": 6},
    "Hawlucha": {"id": 701, "types": ['Fighting', 'Flying'], "generation": 6},
    "Dedenne": {"id": 702, "types": ['Electric', 'Fairy'], "generation": 6},
    "Carbink": {"id": 703, "types": ['Rock', 'Fairy'], "generation": 6},
    "Goomy": {"id": 704, "types": ['Dragon'], "generation": 6},
    "Sliggoo": {"id": 705, "types": ['Dragon'], "generation": 6},
    "Goodra": {"id": 706, "types": ['Dragon'], "generation": 6},
    "Klefki": {"id": 707, "types": ['Steel', 'Fairy'], "generation": 6},
    "Phantump": {"id": 708, "types": ['Ghost', 'Grass'], "generation": 6},
    "Trevenant": {"id": 709, "types": ['Ghost', 'Grass'], "generation": 6},
    "Pumpkaboo": {"id": 710, "types": ['Ghost', 'Grass'], "generation": 6},
    "Gourgeist": {"id": 711, "types": ['Ghost', 'Grass'], "generation": 6},
    "Bergmite": {"id": 712, "types": ['Ice'], "generation": 6},
    "Avalugg": {"id": 713, "types": ['Ice'], "generation": 6},
    "Noibat": {"id": 714, "types": ['Flying', 'Dragon'], "generation": 6},
    "Noivern": {"id": 715, "types": ['Flying', 'Dragon'], "generation": 6},
    "Xerneas": {"id": 716, "types": ['Fairy'], "generation": 6},
    "Yveltal": {"id": 717, "types": ['Dark', 'Flying'], "generation": 6},
    "Zygarde": {"id": 718, "types": ['Dragon', 'Ground'], "generation": 6},
    "Diancie": {"id": 719, "types": ['Rock', 'Fairy'], "generation": 6},
    "Hoopa": {"id": 720, "types": ['Psychic', 'Ghost'], "generation": 6},
    "Volcanion": {"id": 721, "types": ['Fire', 'Water'], "generation": 6},
    "Rowlet": {"id": 722, "types": ['Grass', 'Flying'], "generation": 7},
    "Dartrix": {"id": 723, "types": ['Grass', 'Flying'], "generation": 7},
    "Decidueye": {"id": 724, "types": ['Grass', 'Ghost'], "generation": 7},
    "Litten": {"id": 725, "types": ['Fire'], "generation": 7},
    "Torracat": {"id": 726, "types": ['Fire'], "generation": 7},
    "Incineroar": {"id": 727, "types": ['Fire', 'Dark'], "generation": 7},
    "Popplio": {"id": 728, "types": ['Water'], "generation": 7},
    "Brionne": {"id": 729, "types": ['Water'], "generation": 7},
    "Primarina": {"id": 730, "types": ['Water', 'Fairy'], "generation": 7},
    "Pikipek": {"id": 731, "types": ['Normal', 'Flying'], "generation": 7},
    "Trumbeak": {"id": 732, "types": ['Normal', 'Flying'], "generation": 7},
    "Toucannon": {"id": 733, "types": ['Normal', 'Flying'], "generation": 7},
    "Yungoos": {"id": 734, "types": ['Normal'], "generation": 7},
    "Gumshoos": {"id": 735, "types": ['Normal'], "generation": 7},
    "Grubbin": {"id": 736, "types": ['Bug'], "generation": 7},
    "Charjabug": {"id": 737, "types": ['Bug', 'Electric'], "generation": 7},
    "Vikavolt": {"id": 738, "types": ['Bug', 'Electric'], "generation": 7},
    "Crabrawler": {"id": 739, "types": ['Fighting'], "generation": 7},
    "Crabominable": {"id": 740, "types": ['Fighting', 'Ice'], "generation": 7},
    "Oricorio": {"id": 741, "types": ['Fire', 'Flying'], "generation": 7},
    "Cutiefly": {"id": 742, "types": ['Bug', 'Fairy'], "generation": 7},
    "Ribombee": {"id": 743, "types": ['Bug', 'Fairy'], "generation": 7},
    "Rockruff": {"id": 744, "types": ['Rock'], "generation": 7},
    "Lycanroc": {"id": 745, "types": ['Rock'], "generation": 7},
    "Wishiwashi": {"id": 746, "types": ['Water'], "generation": 7},
    "Mareanie": {"id": 747, "types": ['Poison', 'Water'], "generation": 7},
    "Toxapex": {"id": 748, "types": ['Poison', 'Water'], "generation": 7},
    "Mudbray": {"id": 749, "types": ['Ground'], "generation": 7},
    "Mudsdale": {"id": 750, "types": ['Ground'], "generation": 7},
    "Dewpider": {"id": 751, "types": ['Water', 'Bug'], "generation": 7},
    "Araquanid": {"id": 752, "types": ['Water', 'Bug'], "generation": 7},
    "Fomantis": {"id": 753, "types": ['Grass'], "generation": 7},
    "Lurantis": {"id": 754, "types": ['Grass'], "generation": 7},
    "Morelull": {"id": 755, "types": ['Grass', 'Fairy'], "generation": 7},
    "Shiinotic": {"id": 756, "types": ['Grass', 'Fairy'], "generation": 7},
    "Salandit": {"id": 757, "types": ['Poison', 'Fire'], "generation": 7},
    "Salazzle": {"id": 758, "types": ['Poison', 'Fire'], "generation": 7},
    "Stufful": {"id": 759, "types": ['Normal', 'Fighting'], "generation": 7},
    "Bewear": {"id": 760, "types": ['Normal', 'Fighting'], "generation": 7},
    "Bounsweet": {"id": 761, "types": ['Grass'], "generation": 7},
    "Steenee": {"id": 762, "types": ['Grass'], "generation": 7},
    "Tsareena": {"id": 763, "types": ['Grass'], "generation": 7},
    "Comfey": {"id": 764, "types": ['Fairy'], "generation": 7},
    "Oranguru": {"id": 765, "types": ['Normal', 'Psychic'], "generation": 7},
    "Passimian": {"id": 766, "types": ['Fighting'], "generation": 7},
    "Wimpod": {"id": 767, "types": ['Bug', 'Water'], "generation": 7},
    "Golisopod": {"id": 768, "types": ['Bug', 'Water'], "generation": 7},
    "Sandygast": {"id": 769, "types": ['Ghost', 'Ground'], "generation": 7},
    "Palossand": {"id": 770, "types": ['Ghost', 'Ground'], "generation": 7},
    "Pyukumuku": {"id": 771, "types": ['Water'], "generation": 7},
    "Type: Null": {"id": 772, "types": ['Normal'], "generation": 7},
    "Silvally": {"id": 773, "types": ['Normal'], "generation": 7},
    "Minior": {"id": 774, "types": ['Rock', 'Flying'], "generation": 7},
    "Komala": {"id": 775, "types": ['Normal'], "generation": 7},
    "Turtonator": {"id": 776, "types": ['Fire', 'Dragon'], "generation": 7},
    "Togedemaru": {"id": 777, "types": ['Electric', 'Steel'], "generation": 7},
    "Mimikyu": {"id": 778, "types": ['Ghost', 'Fairy'], "generation": 7},
    "Bruxish": {"id": 779, "types": ['Water', 'Psychic'], "generation": 7},
    "Drampa": {"id": 780, "types": ['Normal', 'Dragon'], "generation": 7},
    "Dhelmise": {"id": 781, "types": ['Ghost', 'Grass'], "generation": 7},
    "Jangmo-o": {"id": 782, "types": ['Dragon'], "generation": 7},
    "Hakamo-o": {"id": 783, "types": ['Dragon', 'Fighting'], "generation": 7},
    "Kommo-o": {"id": 784, "types": ['Dragon', 'Fighting'], "generation": 7},
    "Tapu Koko": {"id": 785, "types": ['Electric', 'Fairy'], "generation": 7},
    "Tapu Lele": {"id": 786, "types": ['Psychic', 'Fairy'], "generation": 7},
    "Tapu Bulu": {"id": 787, "types": ['Grass', 'Fairy'], "generation": 7},
    "Tapu Fini": {"id": 788, "types": ['Water', 'Fairy'], "generation": 7},
    "Cosmog": {"id": 789, "types": ['Psychic'], "generation": 7},
    "Cosmoem": {"id": 790, "types": ['Psychic'], "generation": 7},
    "Solgaleo": {"id": 791, "types": ['Psychic', 'Steel'], "generation": 7},
    "Lunala": {"id": 792, "types": ['Psychic', 'Ghost'], "generation": 7},
    "Nihilego": {"id": 793, "types": ['Rock', 'Poison'], "generation": 7},
    "Buzzwole": {"id": 794, "types": ['Bug', 'Fighting'], "generation": 7},
    "Pheromosa": {"id": 795, "types": ['Bug', 'Fighting'], "generation": 7},
    "Xurkitree": {"id": 796, "types": ['Electric'], "generation": 7},
    "Celesteela": {"id": 797, "types": ['Steel', 'Flying'], "generation": 7},
    "Kartana": {"id": 798, "types": ['Grass', 'Steel'], "generation": 7},
    "Guzzlord": {"id": 799, "types": ['Dark', 'Dragon'], "generation": 7},
    "Necrozma": {"id": 800, "types": ['Psychic'], "generation": 7},
    "Magearna": {"id": 801, "types": ['Steel', 'Fairy'], "generation": 7},
    "Marshadow": {"id": 802, "types": ['Fighting', 'Ghost'], "generation": 7},
    "Poipole": {"id": 803, "types": ['Poison'], "generation": 7},
    "Naganadel": {"id": 804, "types": ['Poison', 'Dragon'], "generation": 7},
    "Stakataka": {"id": 805, "types": ['Rock', 'Steel'], "generation": 7},
    "Blacephalon": {"id": 806, "types": ['Fire', 'Ghost'], "generation": 7},
    "Zeraora": {"id": 807, "types": ['Electric'], "generation": 7},
    "Meltan": {"id": 808, "types": ['Steel'], "generation": 7},
    "Melmetal": {"id": 809, "types": ['Steel'], "generation": 7},
    "Grookey": {"id": 810, "types": ['Grass'], "generation": 8},
    "Thwackey": {"id": 811, "types": ['Grass'], "generation": 8},
    "Rillaboom": {"id": 812, "types": ['Grass'], "generation": 8},
    "Scorbunny": {"id": 813, "types": ['Fire'], "generation": 8},
    "Raboot": {"id": 814, "types": ['Fire'], "generation": 8},
    "Cinderace": {"id": 815, "types": ['Fire'], "generation": 8},
    "Sobble": {"id": 816, "types": ['Water'], "generation": 8},
    "Drizzile": {"id": 817, "types": ['Water'], "generation": 8},
    "Inteleon": {"id": 818, "types": ['Water'], "generation": 8},
    "Skwovet": {"id": 819, "types": ['Normal'], "generation": 8},
    "Greedent": {"id": 820, "types": ['Normal'], "generation": 8},
    "Rookidee": {"id": 821, "types": ['Flying'], "generation": 8},
    "Corvisquire": {"id": 822, "types": ['Flying'], "generation": 8},
    "Corviknight": {"id": 823, "types": ['Flying', 'Steel'], "generation": 8},
    "Blipbug": {"id": 824, "types": ['Bug'], "generation": 8},
    "Dottler": {"id": 825, "types": ['Bug', 'Psychic'], "generation": 8},
    "Orbeetle": {"id": 826, "types": ['Bug', 'Psychic'], "generation": 8},
    "Nickit": {"id": 827, "types": ['Dark'], "generation": 8},
    "Thievul": {"id": 828, "types": ['Dark'], "generation": 8},
    "Gossifleur": {"id": 829, "types": ['Grass'], "generation": 8},
    "Eldegoss": {"id": 830, "types": ['Grass'], "generation": 8},
    "Wooloo": {"id": 831, "types": ['Normal'], "generation": 8},
    "Dubwool": {"id": 832, "types": ['Normal'], "generation": 8},
    "Chewtle": {"id": 833, "types": ['Water'], "generation": 8},
    "Drednaw": {"id": 834, "types": ['Water', 'Rock'], "generation": 8},
    "Yamper": {"id": 835, "types": ['Electric'], "generation": 8},
    "Boltund": {"id": 836, "types": ['Electric'], "generation": 8},
    "Rolycoly": {"id": 837, "types": ['Rock'], "generation": 8},
    "Carkol": {"id": 838, "types": ['Rock', 'Fire'], "generation": 8},
    "Coalossal": {"id": 839, "types": ['Rock', 'Fire'], "generation": 8},
    "Applin": {"id": 840, "types": ['Grass', 'Dragon'], "generation": 8},
    "Flapple": {"id": 841, "types": ['Grass', 'Dragon'], "generation": 8},
    "Appletun": {"id": 842, "types": ['Grass', 'Dragon'], "generation": 8},
    "Silicobra": {"id": 843, "types": ['Ground'], "generation": 8},
    "Sandaconda": {"id": 844, "types": ['Ground'], "generation": 8},
    "Cramorant": {"id": 845, "types": ['Flying', 'Water'], "generation": 8},
    "Arrokuda": {"id": 846, "types": ['Water'], "generation": 8},
    "Barraskewda": {"id": 847, "types": ['Water'], "generation": 8},
    "Toxel": {"id": 848, "types": ['Electric', 'Poison'], "generation": 8},
    "Toxtricity": {"id": 849, "types": ['Electric', 'Poison'], "generation": 8},
    "Sizzlipede": {"id": 850, "types": ['Fire', 'Bug'], "generation": 8},
    "Centiskorch": {"id": 851, "types": ['Fire', 'Bug'], "generation": 8},
    "Clobbopus": {"id": 852, "types": ['Fighting'], "generation": 8},
    "Grapploct": {"id": 853, "types": ['Fighting'], "generation": 8},
    "Sinistea": {"id": 854, "types": ['Ghost'], "generation": 8},
    "Polteageist": {"id": 855, "types": ['Ghost'], "generation": 8},
    "Hatenna": {"id": 856, "types": ['Psychic'], "generation": 8},
    "Hattrem": {"id": 857, "types": ['Psychic'], "generation": 8},
    "Hatterene": {"id": 858, "types": ['Psychic', 'Fairy'], "generation": 8},
    "Impidimp": {"id": 859, "types": ['Dark', 'Fairy'], "generation": 8},
    "Morgrem": {"id": 860, "types": ['Dark', 'Fairy'], "generation": 8},
    "Grimmsnarl": {"id": 861, "types": ['Dark', 'Fairy'], "generation": 8},
    "Obstagoon": {"id": 862, "types": ['Dark', 'Normal'], "generation": 8},
    "Perrserker": {"id": 863, "types": ['Steel'], "generation": 8},
    "Cursola": {"id": 864, "types": ['Ghost'], "generation": 8},
    "Sirfetch'd": {"id": 865, "types": ['Fighting'], "generation": 8},
    "Mr. Rime": {"id": 866, "types": ['Ice', 'Psychic'], "generation": 8},
    "Runerigus": {"id": 867, "types": ['Ground', 'Ghost'], "generation": 8},
    "Milcery": {"id": 868, "types": ['Fairy'], "generation": 8},
    "Alcremie": {"id": 869, "types": ['Fairy'], "generation": 8},
    "Falinks": {"id": 870, "types": ['Fighting'], "generation": 8},
    "Pincurchin": {"id": 871, "types": ['Electric'], "generation": 8},
    "Snom": {"id": 872, "types": ['Ice', 'Bug'], "generation": 8},
    "Frosmoth": {"id": 873, "types": ['Ice', 'Bug'], "generation": 8},
    "Stonjourner": {"id": 874, "types": ['Rock'], "generation": 8},
    "Eiscue": {"id": 875, "types": ['Ice'], "generation": 8},
    "Indeedee": {"id": 876, "types": ['Psychic', 'Normal'], "generation": 8},
    "Morpeko": {"id": 877, "types": ['Electric', 'Dark'], "generation": 8},
    "Cufant": {"id": 878, "types": ['Steel'], "generation": 8},
    "Copperajah": {"id": 879, "types": ['Steel'], "generation": 8},
    "Dracozolt": {"id": 880, "types": ['Electric', 'Dragon'], "generation": 8},
    "Arctozolt": {"id": 881, "types": ['Electric', 'Ice'], "generation": 8},
    "Dracovish": {"id": 882, "types": ['Water', 'Dragon'], "generation": 8},
    "Arctovish": {"id": 883, "types": ['Water', 'Ice'], "generation": 8},
    "Duraludon": {"id": 884, "types": ['Steel', 'Dragon'], "generation": 8},
    "Dreepy": {"id": 885, "types": ['Dragon', 'Ghost'], "generation": 8},
    "Drakloak": {"id": 886, "types": ['Dragon', 'Ghost'], "generation": 8},
    "Dragapult": {"id": 887, "types": ['Dragon', 'Ghost'], "generation": 8},
    "Zacian": {"id": 888, "types": ['Fairy'], "generation": 8},
    "Zamazenta": {"id": 889, "types": ['Fighting'], "generation": 8},
    "Eternatus": {"id": 890, "types": ['Poison', 'Dragon'], "generation": 8},
    "Kubfu": {"id": 891, "types": ['Fighting'], "generation": 8},
    "Urshifu": {"id": 892, "types": ['Fighting', 'Dark'], "generation": 8},
    "Zarude": {"id": 893, "types": ['Dark', 'Grass'], "generation": 8},
    "Regieleki": {"id": 894, "types": ['Electric'], "generation": 8},
    "Regidrago": {"id": 895, "types": ['Dragon'], "generation": 8},
    "Glastrier": {"id": 896, "types": ['Ice'], "generation": 8},
    "Spectrier": {"id": 897, "types": ['Ghost'], "generation": 8},
    "Calyrex": {"id": 898, "types": ['Psychic', 'Grass'], "generation": 8},
    "Wyrdeer": {"id": 899, "types": ['Normal', 'Psychic'], "generation": 8},
    "Kleavor": {"id": 900, "types": ['Bug', 'Rock'], "generation": 8},
    "Ursaluna": {"id": 901, "types": ['Ground', 'Normal'], "generation": 8},
    "Basculegion": {"id": 902, "types": ['Water', 'Ghost'], "generation": 8},
    "Sneasler": {"id": 903, "types": ['Fighting', 'Poison'], "generation": 8},
    "Overqwil": {"id": 904, "types": ['Dark', 'Poison'], "generation": 8},
    "Enamorus": {"id": 905, "types": ['Fairy', 'Flying'], "generation": 8},
    "Sprigatito": {"id": 906, "types": ['Grass'], "generation": 9},
    "Floragato": {"id": 907, "types": ['Grass'], "generation": 9},
    "Meowscarada": {"id": 908, "types": ['Grass', 'Dark'], "generation": 9},
    "Fuecoco": {"id": 909, "types": ['Fire'], "generation": 9},
    "Crocalor": {"id": 910, "types": ['Fire'], "generation": 9},
    "Skeledirge": {"id": 911, "types": ['Fire', 'Ghost'], "generation": 9},
    "Quaxly": {"id": 912, "types": ['Water'], "generation": 9},
    "Quaxwell": {"id": 913, "types": ['Water'], "generation": 9},
    "Quaquaval": {"id": 914, "types": ['Water', 'Fighting'], "generation": 9},
    "Lechonk": {"id": 915, "types": ['Normal'], "generation": 9},
    "Oinkologne": {"id": 916, "types": ['Normal'], "generation": 9},
    "Tarountula": {"id": 917, "types": ['Bug'], "generation": 9},
    "Spidops": {"id": 918, "types": ['Bug'], "generation": 9},
    "Nymble": {"id": 919, "types": ['Bug'], "generation": 9},
    "Lokix": {"id": 920, "types": ['Bug', 'Dark'], "generation": 9},
    "Pawmi": {"id": 921, "types": ['Electric'], "generation": 9},
    "Pawmo": {"id": 922, "types": ['Electric', 'Fighting'], "generation": 9},
    "Pawmot": {"id": 923, "types": ['Electric', 'Fighting'], "generation": 9},
    "Tandemaus": {"id": 924, "types": ['Normal'], "generation": 9},
    "Maushold": {"id": 925, "types": ['Normal'], "generation": 9},
    "Fidough": {"id": 926, "types": ['Fairy'], "generation": 9},
    "Dachsbun": {"id": 927, "types": ['Fairy'], "generation": 9},
    "Smoliv": {"id": 928, "types": ['Grass', 'Normal'], "generation": 9},
    "Dolliv": {"id": 929, "types": ['Grass', 'Normal'], "generation": 9},
    "Arboliva": {"id": 930, "types": ['Grass', 'Normal'], "generation": 9},
    "Squawkabilly": {"id": 931, "types": ['Normal', 'Flying'], "generation": 9},
    "Nacli": {"id": 932, "types": ['Rock'], "generation": 9},
    "Naclstack": {"id": 933, "types": ['Rock'], "generation": 9},
    "Garganacl": {"id": 934, "types": ['Rock'], "generation": 9},
    "Charcadet": {"id": 935, "types": ['Fire'], "generation": 9},
    "Armarouge": {"id": 936, "types": ['Fire', 'Psychic'], "generation": 9},
    "Ceruledge": {"id": 937, "types": ['Fire', 'Ghost'], "generation": 9},
    "Tadbulb": {"id": 938, "types": ['Electric'], "generation": 9},
    "Bellibolt": {"id": 939, "types": ['Electric'], "generation": 9},
    "Wattrel": {"id": 940, "types": ['Electric', 'Flying'], "generation": 9},
    "Kilowattrel": {"id": 941, "types": ['Electric', 'Flying'], "generation": 9},
    "Maschiff": {"id": 942, "types": ['Dark'], "generation": 9},
    "Mabosstiff": {"id": 943, "types": ['Dark'], "generation": 9},
    "Shroodle": {"id": 944, "types": ['Poison', 'Normal'], "generation": 9},
    "Grafaiai": {"id": 945, "types": ['Poison', 'Normal'], "generation": 9},
    "Bramblin": {"id": 946, "types": ['Grass', 'Ghost'], "generation": 9},
    "Brambleghast": {"id": 947, "types": ['Grass', 'Ghost'], "generation": 9},
    "Toedscool": {"id": 948, "types": ['Ground', 'Grass'], "generation": 9},
    "Toedscruel": {"id": 949, "types": ['Ground', 'Grass'], "generation": 9},
    "Klawf": {"id": 950, "types": ['Rock'], "generation": 9},
    "Capsakid": {"id": 951, "types": ['Grass'], "generation": 9},
    "Scovillain": {"id": 952, "types": ['Grass', 'Fire'], "generation": 9},
    "Rellor": {"id": 953, "types": ['Bug'], "generation": 9},
    "Rabsca": {"id": 954, "types": ['Bug', 'Psychic'], "generation": 9},
    "Flittle": {"id": 955, "types": ['Psychic'], "generation": 9},
    "Espathra": {"id": 956, "types": ['Psychic'], "generation": 9},
    "Tinkatink": {"id": 957, "types": ['Fairy', 'Steel'], "generation": 9},
    "Tinkatuff": {"id": 958, "types": ['Fairy', 'Steel'], "generation": 9},
    "Tinkaton": {"id": 959, "types": ['Fairy', 'Steel'], "generation": 9},
    "Wiglett": {"id": 960, "types": ['Water'], "generation": 9},
    "Wugtrio": {"id": 961, "types": ['Water'], "generation": 9},
    "Bombirdier": {"id": 962, "types": ['Flying', 'Dark'], "generation": 9},
    "Finizen": {"id": 963, "types": ['Water'], "generation": 9},
    "Palafin": {"id": 964, "types": ['Water'], "generation": 9},
    "Varoom": {"id": 965, "types": ['Steel', 'Poison'], "generation": 9},
    "Revavroom": {"id": 966, "types": ['Steel', 'Poison'], "generation": 9},
    "Cyclizar": {"id": 967, "types": ['Dragon', 'Normal'], "generation": 9},
    "Orthworm": {"id": 968, "types": ['Steel'], "generation": 9},
    "Glimmet": {"id": 969, "types": ['Rock', 'Poison'], "generation": 9},
    "Glimmora": {"id": 970, "types": ['Rock', 'Poison'], "generation": 9},
    "Greavard": {"id": 971, "types": ['Ghost'], "generation": 9},
    "Houndstone": {"id": 972, "types": ['Ghost'], "generation": 9},
    "Flamigo": {"id": 973, "types": ['Flying', 'Fighting'], "generation": 9},
    "Cetoddle": {"id": 974, "types": ['Ice'], "generation": 9},
    "Cetitan": {"id": 975, "types": ['Ice'], "generation": 9},
    "Veluza": {"id": 976, "types": ['Water', 'Psychic'], "generation": 9},
    "Dondozo": {"id": 977, "types": ['Water'], "generation": 9},
    "Tatsugiri": {"id": 978, "types": ['Dragon', 'Water'], "generation": 9},
    "Annihilape": {"id": 979, "types": ['Fighting', 'Ghost'], "generation": 9},
    "Clodsire": {"id": 980, "types": ['Poison', 'Ground'], "generation": 9},
    "Farigiraf": {"id": 981, "types": ['Normal', 'Psychic'], "generation": 9},
    "Dudunsparce": {"id": 982, "types": ['Normal'], "generation": 9},
    "Kingambit": {"id": 983, "types": ['Dark', 'Steel'], "generation": 9},
    "Great Tusk": {"id": 984, "types": ['Ground', 'Fighting'], "generation": 9},
    "Scream Tail": {"id": 985, "types": ['Fairy', 'Psychic'], "generation": 9},
    "Brute Bonnet": {"id": 986, "types": ['Grass', 'Dark'], "generation": 9},
    "Flutter Mane": {"id": 987, "types": ['Ghost', 'Fairy'], "generation": 9},
    "Slither Wing": {"id": 988, "types": ['Bug', 'Fighting'], "generation": 9},
    "Sandy Shocks": {"id": 989, "types": ['Electric', 'Ground'], "generation": 9},
    "Iron Treads": {"id": 990, "types": ['Ground', 'Steel'], "generation": 9},
    "Iron Bundle": {"id": 991, "types": ['Ice', 'Water'], "generation": 9},
    "Iron Hands": {"id": 992, "types": ['Fighting', 'Electric'], "generation": 9},
    "Iron Jugulis": {"id": 993, "types": ['Dark', 'Flying'], "generation": 9},
    "Iron Moth": {"id": 994, "types": ['Fire', 'Poison'], "generation": 9},
    "Iron Thorns": {"id": 995, "types": ['Rock', 'Electric'], "generation": 9},
    "Frigibax": {"id": 996, "types": ['Dragon', 'Ice'], "generation": 9},
    "Arctibax": {"id": 997, "types": ['Dragon', 'Ice'], "generation": 9},
    "Baxcalibur": {"id": 998, "types": ['Dragon', 'Ice'], "generation": 9},
    "Gimmighoul": {"id": 999, "types": ['Ghost'], "generation": 9},
    "Gholdengo": {"id": 1000, "types": ['Steel', 'Ghost'], "generation": 9},
    "Wo-Chien": {"id": 1001, "types": ['Dark', 'Grass'], "generation": 9},
    "Chien-Pao": {"id": 1002, "types": ['Dark', 'Ice'], "generation": 9},
    "Ting-Lu": {"id": 1003, "types": ['Dark', 'Ground'], "generation": 9},
    "Chi-Yu": {"id": 1004, "types": ['Dark', 'Fire'], "generation": 9},
    "Roaring Moon": {"id": 1005, "types": ['Dragon', 'Dark'], "generation": 9},
    "Iron Valiant": {"id": 1006, "types": ['Fairy', 'Fighting'], "generation": 9},
    "Koraidon": {"id": 1007, "types": ['Fighting', 'Dragon'], "generation": 9},
    "Miraidon": {"id": 1008, "types": ['Electric', 'Dragon'], "generation": 9},
    "Walking Wake": {"id": 1009, "types": ['Water', 'Dragon'], "generation": 9},
    "Iron Leaves": {"id": 1010, "types": ['Grass', 'Psychic'], "generation": 9},
    "Dipplin": {"id": 1011, "types": ['Grass', 'Dragon'], "generation": 9},
    "Poltchageist": {"id": 1012, "types": ['Grass', 'Ghost'], "generation": 9},
    "Sinistcha": {"id": 1013, "types": ['Grass', 'Ghost'], "generation": 9},
    "Okidogi": {"id": 1014, "types": ['Poison', 'Fighting'], "generation": 9},
    "Munkidori": {"id": 1015, "types": ['Poison', 'Psychic'], "generation": 9},
    "Fezandipiti": {"id": 1016, "types": ['Poison', 'Fairy'], "generation": 9},
    "Ogerpon": {"id": 1017, "types": ['Grass'], "generation": 9},
    "Archaludon": {"id": 1018, "types": ['Steel', 'Dragon'], "generation": 9},
    "Hydrapple": {"id": 1019, "types": ['Grass', 'Dragon'], "generation": 9},
    "Gouging Fire": {"id": 1020, "types": ['Fire', 'Dragon'], "generation": 9},
    "Raging Bolt": {"id": 1021, "types": ['Electric', 'Dragon'], "generation": 9},
    "Iron Boulder": {"id": 1022, "types": ['Rock', 'Psychic'], "generation": 9},
    "Iron Crown": {"id": 1023, "types": ['Steel', 'Psychic'], "generation": 9},
    "Terapagos": {"id": 1024, "types": ['Normal'], "generation": 9},
    "Pecharunt": {"id": 1025, "types": ['Poison', 'Ghost'], "generation": 9},
}

def get_pokemon_sprite_url(pokemon_id):
    """Get sprite URL from GitHub official artwork"""
    return f"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/{pokemon_id}.png"

def get_pokemon_info_local(name):
    """Get Pokemon info from local database"""
    if name in POKEMON_DATA:
        data = POKEMON_DATA[name]
        pokemon_id = data["id"]
        sprite_url = get_pokemon_sprite_url(pokemon_id)
        
        # Get height and weight from official data
        height = None
        weight = None
        from official_pokemon_data import OFFICIAL_POKEMON_DATA
        if pokemon_id in OFFICIAL_POKEMON_DATA:
            official = OFFICIAL_POKEMON_DATA[pokemon_id]
            height = official.get('height_m', 0)
            weight = official.get('weight_kg', 0)
        
        return {
            "name": name,
            "id": pokemon_id,
            "types": data["types"],
            "generation": f"Generation {data['generation']}",
            "generation_display": data['generation'],
            "sprite": sprite_url,
            "height": height or 0,
            "weight": weight or 0,
            "color": "unknown"
        }
    return None
